export const agents = [
  {
    id: "agent-01",
    name: "Priya Chandrasekaran",
    email: "priya.c@supportdesk.io",
    teamId: "team-frontline",
    title: "Support Agent",
  },
  {
    id: "agent-02",
    name: "Marcus Webb",
    email: "marcus.webb@supportdesk.io",
    teamId: "team-frontline",
    title: "Support Agent",
  },
  {
    id: "agent-03",
    name: "Elena Kovac",
    email: "elena.kovac@supportdesk.io",
    teamId: "team-billing",
    title: "Billing Specialist",
  },
  {
    id: "agent-04",
    name: "Tomas Rivera",
    email: "tomas.rivera@supportdesk.io",
    teamId: "team-billing",
    title: "Billing Specialist",
  },
  {
    id: "agent-05",
    name: "Aisha Bello",
    email: "aisha.bello@supportdesk.io",
    teamId: "team-technical",
    title: "Senior Technical Agent",
  },
  {
    id: "agent-06",
    name: "Daniel Osei",
    email: "daniel.osei@supportdesk.io",
    teamId: "team-technical",
    title: "Technical Agent",
  },
  {
    id: "agent-07",
    name: "Hana Kobayashi",
    email: "hana.kobayashi@supportdesk.io",
    teamId: "team-frontline",
    title: "Team Lead",
  },
  {
    id: "agent-08",
    name: "Liam O'Connell",
    email: "liam.oconnell@supportdesk.io",
    teamId: "team-technical",
    title: "Technical Agent",
  },
];
