export const customers = [
  {
    id: "cust-01",
    name: "Grace Whitfield",
    email: "grace.whitfield@northfieldlogistics.com",
    company: "Northfield Logistics",
    plan: "Business",
  },
  {
    id: "cust-02",
    name: "Owen Marsh",
    email: "owen.marsh@brightlanemedia.com",
    company: "Brightlane Media",
    plan: "Pro",
  },
  {
    id: "cust-03",
    name: "Sofia Almeida",
    email: "sofia.almeida@dunehealth.io",
    company: "Dune Health",
    plan: "Enterprise",
  },
  {
    id: "cust-04",
    name: "Jason Pryce",
    email: "jpryce@harborworks.co",
    company: "Harborworks",
    plan: "Starter",
  },
  {
    id: "cust-05",
    name: "Meera Iyer",
    email: "meera.iyer@cascadefinancial.com",
    company: "Cascade Financial",
    plan: "Enterprise",
  },
  {
    id: "cust-06",
    name: "Callum Barrett",
    email: "callum.b@fernretail.com",
    company: "Fern Retail Group",
    plan: "Pro",
  },
  {
    id: "cust-07",
    name: "Ingrid Solberg",
    email: "ingrid.solberg@polarisstudio.no",
    company: "Polaris Studio",
    plan: "Business",
  },
  {
    id: "cust-08",
    name: "Tariq Hassan",
    email: "tariq.hassan@vellummedia.com",
    company: "Vellum Media",
    plan: "Starter",
  },
  {
    id: "cust-09",
    name: "Chloe Bennett",
    email: "chloe.bennett@driftwear.com",
    company: "Driftwear",
    plan: "Pro",
  },
  {
    id: "cust-10",
    name: "Noah Fischer",
    email: "noah.fischer@granitepeak.dev",
    company: "Granite Peak Dev",
    plan: "Business",
  },
];
